# Generated by Django 3.2.16 on 2022-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_urlss',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(help_text='decrypted_key', max_length=5000, null=True)),
                ('complete_short_url', models.CharField(help_text='complete_short_url', max_length=5000, null=True)),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
                ('file_id', models.IntegerField(help_text='file_id', max_length=5000, null=True)),
            ],
            options={
                'db_table': 'urls_information',
            },
        ),
    ]
